# Generated by Django 5.0.4 on 2024-04-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.IntegerField(null=True)),
                ('seat', models.IntegerField(null=True)),
                ('thigh', models.IntegerField(null=True)),
                ('fagh', models.IntegerField(null=True)),
                ('pants', models.IntegerField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.size')),
            ],
        ),
    ]
