# Generated by Django 5.0.4 on 2024-04-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_size_info_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size_info',
            name='name1',
        ),
        migrations.AlterField(
            model_name='size_info',
            name='name',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='clothes.size'),
        ),
    ]
