# Generated by Django 5.0.4 on 2024-04-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_remove_size_info_name1_alter_size_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='size_info',
            name='info',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.clothing'),
        ),
    ]
